### ISSUE TITLE
NoClassDefFoundError on 3.2.1

### ISSUE THREAD

**Issue by ghost** [magnusulf/MassiveCore#2]
Hello and thank you for maintaining this plugin.
## Affected Plugin

- **Affected Plugin Name:** MassiveCore
- **Affected Plugin Version:** 3.2.1

## Describe your Environment

- **Server Version:** Spigot 1.13.2 "Final" build

## Steps to Reproduce this Bug

On a "fresh" spigot server, the following error occur during startup :
https://pastebin.com/xVJEHUsA
As a consequence, the plugin is not loaded and Factions cannot load after that.
The error does **not** occur on the 3.2.0 version.

**Comment by magnusulf** [comment]
This was fixed in 3.2.2
