### ISSUE TITLE
Error + Server Crash

### ISSUE THREAD

**Issue by halberfan** [magnusulf/MassiveCore#3]
Newest MassiveCore and Factions Version (by you)
Server Version: 1.14.4 (gitPaper - 173)
The server crashes after that occoures

Stacktrace: https://pastebin.com/WGGeV4B8

(Sorry for didn't answer last time, forgot it: it got fixed by itself)

**Comment by magnusulf** [comment]
This is in fact a Factions bug but I have fixed it now.
